# Generated by Django 2.1.4 on 2019-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=16)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
